import {
  Atom,
  BrainCircuit,
  Bot,
  Boxes,
  Cloud,
  CloudCog,
  Code2,
  Component,
  Container,
  Cpu,
  Database,
  Eye,
  Feather,
  Figma,
  FileCode2,
  FlaskConical,
  Gauge,
  GitBranch,
  GitMerge,
  GraduationCap,
  Heart,
  Layers,
  LayoutGrid,
  Leaf,
  Palette,
  Paintbrush,
  PenTool,
  PlayCircle,
  RefreshCw,
  Rocket,
  Send,
  Server,
  Smartphone,
  Sparkles,
  TestTube,
  TestTube2,
  Terminal,
  TrendingUp,
  Triangle,
  Wand2,
  Waves,
  Workflow,
  Wrench,
  Zap,
} from "lucide-react";
import type { EngineeringPrinciple, Skill, SkillCategory } from "@/types/skill";

export const SKILL_CATEGORIES: SkillCategory[] = [
  {
    id: "frontend",
    title: "Frontend",
    description: "Building fast, accessible interfaces with modern component architecture.",
    icon: Code2,
    skillIds: ["react", "nextjs", "typescript"],
  },
  {
    id: "backend",
    title: "Backend",
    description: "Designing reliable APIs and services that hold up under real traffic.",
    icon: Server,
    skillIds: ["nodejs", "express", "nestjs"],
  },
  {
    id: "mobile",
    title: "Mobile",
    description: "Shipping cross-platform apps that feel native on every device.",
    icon: Smartphone,
    skillIds: ["react-native", "expo", "swift"],
  },
  {
    id: "ui-frameworks",
    title: "UI Frameworks",
    description: "Composing consistent, accessible interfaces from proven primitives.",
    icon: LayoutGrid,
    skillIds: ["shadcn", "radix", "mui"],
  },
  {
    id: "state-management",
    title: "State Management",
    description: "Keeping application state predictable, testable, and fast.",
    icon: Boxes,
    skillIds: ["redux-toolkit", "zustand", "tanstack-query"],
  },
  {
    id: "styling",
    title: "Styling",
    description: "Crafting design systems with utility-first and scoped styling tools.",
    icon: Palette,
    skillIds: ["tailwind", "css-modules", "sass"],
  },
  {
    id: "animation",
    title: "Animation",
    description: "Adding motion that clarifies interactions instead of distracting from them.",
    icon: Sparkles,
    skillIds: ["framer-motion", "gsap", "lottie"],
  },
  {
    id: "databases",
    title: "Databases",
    description: "Modeling data that stays consistent as products grow in complexity.",
    icon: Database,
    skillIds: ["postgresql", "supabase", "mongodb"],
  },
  {
    id: "cloud",
    title: "Cloud",
    description: "Deploying and scaling infrastructure with confidence.",
    icon: Cloud,
    skillIds: ["vercel", "aws", "docker"],
  },
  {
    id: "devops",
    title: "DevOps",
    description: "Automating delivery so shipping software feels routine, not risky.",
    icon: Workflow,
    skillIds: ["github-actions", "cicd", "terraform"],
  },
  {
    id: "testing",
    title: "Testing",
    description: "Writing tests that catch regressions before users ever do.",
    icon: FlaskConical,
    skillIds: ["jest", "playwright", "rtl"],
  },
  {
    id: "tools",
    title: "Tools",
    description: "Using the right tooling to move fast without sacrificing quality.",
    icon: Wrench,
    skillIds: ["git", "vscode", "postman"],
  },
  {
    id: "ai",
    title: "AI",
    description: "Integrating AI tooling into everyday engineering workflows.",
    icon: BrainCircuit,
    skillIds: ["openai", "claude", "copilot"],
  },
  {
    id: "design",
    title: "Design",
    description: "Bridging design and engineering to ship cohesive product experiences.",
    icon: PenTool,
    skillIds: ["figma", "design-systems", "prototyping"],
  },
];

export const SKILLS: Skill[] = [
  { id: "react", name: "React", categoryId: "frontend", category: "Frontend", description: "Building component-driven UIs with a focus on composition and reusability.", level: "expert", icon: Atom },
  { id: "nextjs", name: "Next.js", categoryId: "frontend", category: "Frontend", description: "Shipping production apps with the App Router, server components, and edge rendering.", level: "expert", icon: Layers },
  { id: "typescript", name: "TypeScript", categoryId: "frontend", category: "Frontend", description: "Using strict typing to catch bugs early and keep large codebases maintainable.", level: "expert", icon: FileCode2 },

  { id: "nodejs", name: "Node.js", categoryId: "backend", category: "Backend", description: "Building server-side services and tooling on top of the Node runtime.", level: "advanced", icon: Server },
  { id: "express", name: "Express", categoryId: "backend", category: "Backend", description: "Standing up lightweight REST APIs with clear middleware boundaries.", level: "advanced", icon: Terminal },
  { id: "nestjs", name: "NestJS", categoryId: "backend", category: "Backend", description: "Structuring larger backend services with modular, testable architecture.", level: "comfortable", icon: Cpu },

  { id: "react-native", name: "React Native", categoryId: "mobile", category: "Mobile", description: "Sharing logic between web and mobile without compromising native feel.", level: "comfortable", icon: Smartphone },
  { id: "expo", name: "Expo", categoryId: "mobile", category: "Mobile", description: "Speeding up mobile builds and releases with a managed workflow.", level: "comfortable", icon: Rocket },
  { id: "swift", name: "Swift", categoryId: "mobile", category: "Mobile", description: "Exploring native iOS development for performance-critical experiences.", level: "learning", icon: Feather },

  { id: "shadcn", name: "shadcn/ui", categoryId: "ui-frameworks", category: "UI Frameworks", description: "Composing accessible, unstyled primitives into a cohesive design system.", level: "expert", icon: Component },
  { id: "radix", name: "Radix UI", categoryId: "ui-frameworks", category: "UI Frameworks", description: "Relying on accessible primitives for complex interaction patterns.", level: "advanced", icon: Boxes },
  { id: "mui", name: "Material UI", categoryId: "ui-frameworks", category: "UI Frameworks", description: "Working within established design systems for enterprise dashboards.", level: "comfortable", icon: LayoutGrid },

  { id: "redux-toolkit", name: "Redux Toolkit", categoryId: "state-management", category: "State Management", description: "Managing complex, shared state with predictable update patterns.", level: "advanced", icon: Boxes },
  { id: "zustand", name: "Zustand", categoryId: "state-management", category: "State Management", description: "Reaching for minimal, hook-based state when Redux is more than needed.", level: "expert", icon: GitBranch },
  { id: "tanstack-query", name: "TanStack Query", categoryId: "state-management", category: "State Management", description: "Handling server state, caching, and background sync without boilerplate.", level: "advanced", icon: RefreshCw },

  { id: "tailwind", name: "Tailwind CSS", categoryId: "styling", category: "Styling", description: "Building design systems with utility classes mapped to design tokens.", level: "expert", icon: Palette },
  { id: "css-modules", name: "CSS Modules", categoryId: "styling", category: "Styling", description: "Scoping styles locally when a project calls for plain CSS.", level: "advanced", icon: FileCode2 },
  { id: "sass", name: "Sass", categoryId: "styling", category: "Styling", description: "Organizing larger stylesheets with variables, mixins, and nesting.", level: "comfortable", icon: Paintbrush },

  { id: "framer-motion", name: "Framer Motion", categoryId: "animation", category: "Animation", description: "Choreographing interface motion that feels physical and intentional.", level: "expert", icon: Sparkles },
  { id: "gsap", name: "GSAP", categoryId: "animation", category: "Animation", description: "Building complex timeline-based animations for marketing sites.", level: "comfortable", icon: Waves },
  { id: "lottie", name: "Lottie", categoryId: "animation", category: "Animation", description: "Bringing designer-created animations into production without rebuilding them.", level: "comfortable", icon: PlayCircle },

  { id: "postgresql", name: "PostgreSQL", categoryId: "databases", category: "Databases", description: "Modeling relational data with confidence in constraints and query performance.", level: "advanced", icon: Database },
  { id: "supabase", name: "Supabase", categoryId: "databases", category: "Databases", description: "Shipping full-stack features fast with managed Postgres and auth.", level: "advanced", icon: Zap },
  { id: "mongodb", name: "MongoDB", categoryId: "databases", category: "Databases", description: "Using document stores for flexible, evolving data shapes.", level: "comfortable", icon: Leaf },

  { id: "vercel", name: "Vercel", categoryId: "cloud", category: "Cloud", description: "Deploying frontend infrastructure with zero-config edge performance.", level: "expert", icon: Triangle },
  { id: "aws", name: "AWS", categoryId: "cloud", category: "Cloud", description: "Provisioning core cloud infrastructure for backend and data workloads.", level: "comfortable", icon: CloudCog },
  { id: "docker", name: "Docker", categoryId: "cloud", category: "Cloud", description: "Containerizing services for consistent local and production environments.", level: "advanced", icon: Container },

  { id: "github-actions", name: "GitHub Actions", categoryId: "devops", category: "DevOps", description: "Automating tests, previews, and deployments on every pull request.", level: "advanced", icon: Workflow },
  { id: "cicd", name: "CI/CD Pipelines", categoryId: "devops", category: "DevOps", description: "Designing delivery pipelines that catch issues before production.", level: "advanced", icon: GitMerge },
  { id: "terraform", name: "Terraform", categoryId: "devops", category: "DevOps", description: "Describing infrastructure as code for repeatable environments.", level: "learning", icon: Layers },

  { id: "jest", name: "Jest", categoryId: "testing", category: "Testing", description: "Covering business logic with fast, isolated unit tests.", level: "advanced", icon: TestTube2 },
  { id: "playwright", name: "Playwright", categoryId: "testing", category: "Testing", description: "Automating end-to-end flows across browsers before every release.", level: "advanced", icon: TestTube },
  { id: "rtl", name: "React Testing Library", categoryId: "testing", category: "Testing", description: "Testing components the way real users actually interact with them.", level: "expert", icon: PlayCircle },

  { id: "git", name: "Git", categoryId: "tools", category: "Tools", description: "Keeping history clean and collaboration friction-free on every team.", level: "expert", icon: GitBranch },
  { id: "vscode", name: "VS Code", categoryId: "tools", category: "Tools", description: "Tuning editor tooling and extensions for a fast daily workflow.", level: "expert", icon: Terminal },
  { id: "postman", name: "Postman", categoryId: "tools", category: "Tools", description: "Documenting and testing APIs before they reach frontend consumers.", level: "advanced", icon: Send },

  { id: "openai", name: "OpenAI API", categoryId: "ai", category: "AI", description: "Building AI-assisted features on top of production LLM APIs.", level: "advanced", icon: Bot },
  { id: "claude", name: "Claude", categoryId: "ai", category: "AI", description: "Using Claude for planning, reviewing, and pairing on real engineering work.", level: "expert", icon: Sparkles },
  { id: "copilot", name: "GitHub Copilot", categoryId: "ai", category: "AI", description: "Pairing with AI tooling to move faster on repetitive implementation work.", level: "advanced", icon: Wand2 },

  { id: "figma", name: "Figma", categoryId: "design", category: "Design", description: "Collaborating directly in design files to keep engineering and design aligned.", level: "advanced", icon: Figma },
  { id: "design-systems", name: "Design Systems", categoryId: "design", category: "Design", description: "Translating design tokens into consistent, reusable component libraries.", level: "expert", icon: LayoutGrid },
  { id: "prototyping", name: "Prototyping", categoryId: "design", category: "Design", description: "Validating interaction ideas quickly before committing to full builds.", level: "comfortable", icon: PenTool },
];

export const ENGINEERING_PRINCIPLES: EngineeringPrinciple[] = [
  {
    id: "clean-architecture",
    title: "Clean Architecture",
    description: "Structuring code around clear boundaries so features can evolve without rewrites.",
    icon: Boxes,
  },
  {
    id: "performance-first",
    title: "Performance First",
    description: "Treating load time and responsiveness as core features, not afterthoughts.",
    icon: Gauge,
  },
  {
    id: "accessibility",
    title: "Accessibility",
    description: "Designing for keyboard, screen reader, and low-vision users from day one.",
    icon: Eye,
  },
  {
    id: "scalability",
    title: "Scalability",
    description: "Making decisions today that hold up as teams and traffic grow tomorrow.",
    icon: TrendingUp,
  },
  {
    id: "developer-experience",
    title: "Developer Experience",
    description: "Investing in tooling and documentation that keep teams shipping confidently.",
    icon: Heart,
  },
  {
    id: "testing",
    title: "Testing",
    description: "Covering critical paths with tests that give real confidence to deploy.",
    icon: FlaskConical,
  },
  {
    id: "continuous-learning",
    title: "Continuous Learning",
    description: "Staying curious about new tools while knowing when to stick with the basics.",
    icon: GraduationCap,
  },
];
